-- Core entities
CREATE SEQUENCE STUDENTS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE COHORTS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE COURSES_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE COURSE_GROUPS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE DELIVERABLES_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE NOTIFICATIONS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE STUDENTS (
    id          NUMBER DEFAULT STUDENTS_SEQ.NEXTVAL NOT NULL,
    name        VARCHAR2(255) NOT NULL,
    email       VARCHAR2(320) NOT NULL UNIQUE,
    is_admin    NUMBER(1)
                    DEFAULT 0
                    NOT NULL
                    CONSTRAINT STUDENTS_ADMIN_CHK
                        CHECK (is_admin IN (0,1)),
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT STUDENTS_PK PRIMARY KEY (id)
);

CREATE TABLE COHORTS (
    id          NUMBER DEFAULT COHORTS_SEQ.NEXTVAL NOT NULL,
    name        VARCHAR2(255) NOT NULL UNIQUE,
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT COHORTS_PK PRIMARY KEY (id)
);

CREATE TABLE COURSES (
    id          NUMBER DEFAULT COURSES_SEQ.NEXTVAL NOT NULL,
    name        VARCHAR2(255) NOT NULL UNIQUE,
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT COURSES_PK PRIMARY KEY (id)
);

CREATE TABLE COURSE_GROUPS (
    id          NUMBER DEFAULT COURSE_GROUPS_SEQ.NEXTVAL NOT NULL,
    course_id   NUMBER NOT NULL,
    name        VARCHAR2(255) NOT NULL,
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT COURSE_GROUPS_PK PRIMARY KEY (id),
    CONSTRAINT COURSE_GROUPS_COURSE_NAME_UK
        UNIQUE (course_id, name),
    CONSTRAINT COURSE_GROUPS_COURSE_FK
        FOREIGN KEY (course_id) REFERENCES COURSES(id)
        ON DELETE CASCADE
);

CREATE TABLE DELIVERABLES (
    id              NUMBER DEFAULT DELIVERABLES_SEQ.NEXTVAL NOT NULL,
    course_group_id NUMBER NOT NULL,
    name            VARCHAR2(255) NOT NULL,
    deadline        TIMESTAMP NOT NULL,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT DELIVERABLES_PK PRIMARY KEY (id),
    CONSTRAINT DELIVERABLES_COURSE_GROUP_NAME_UK
        UNIQUE (course_group_id, name),
    CONSTRAINT DELIVERABLES_COURSE_GROUP_FK
        FOREIGN KEY (course_group_id) REFERENCES COURSE_GROUPS(id)
        ON DELETE CASCADE
);

CREATE TABLE NOTIFICATIONS (
    id             NUMBER DEFAULT NOTIFICATIONS_SEQ.NEXTVAL NOT NULL,
    deliverable_id NUMBER,
    course_id      NUMBER,
    title          VARCHAR2(255) NOT NULL,
    message        VARCHAR2(4000),
    created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT NOTIFICATIONS_PK PRIMARY KEY (id),
    CONSTRAINT NOTIFICATIONS_DELIVERABLE_FK
        FOREIGN KEY (deliverable_id) REFERENCES DELIVERABLES(id)
        ON DELETE CASCADE,
    CONSTRAINT NOTIFICATIONS_COURSE_FK
        FOREIGN KEY (course_id) REFERENCES COURSES(id)
        ON DELETE CASCADE,
    CONSTRAINT NOTIFICATIONS_TARGET_CHK
        CHECK (deliverable_id IS NOT NULL OR course_id IS NOT NULL)
);

-- Many-to-many junction tables
CREATE TABLE STUDENTS_COHORTS (
    student_id  NUMBER NOT NULL,
    cohort_id   NUMBER NOT NULL,
    enrolled_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT STUDENTS_COHORTS_PK PRIMARY KEY (student_id, cohort_id),
    CONSTRAINT STUDENTS_COHORTS_STUDENT_FK
        FOREIGN KEY (student_id) REFERENCES STUDENTS(id)
        ON DELETE CASCADE,
    CONSTRAINT STUDENTS_COHORTS_COHORT_FK
        FOREIGN KEY (cohort_id) REFERENCES COHORTS(id)
        ON DELETE CASCADE
);

CREATE TABLE COHORTS_COURSES (
    cohort_id   NUMBER NOT NULL,
    course_id   NUMBER NOT NULL,
    added_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT COHORTS_COURSES_PK PRIMARY KEY (cohort_id, course_id),
    CONSTRAINT COHORTS_COURSES_COHORT_FK
        FOREIGN KEY (cohort_id) REFERENCES COHORTS(id)
        ON DELETE CASCADE,
    CONSTRAINT COHORTS_COURSES_COURSE_FK
        FOREIGN KEY (course_id) REFERENCES COURSES(id)
        ON DELETE CASCADE
);

CREATE TABLE STUDENTS_COURSE_GROUPS (
    student_id       NUMBER NOT NULL,
    course_group_id  NUMBER NOT NULL,
    followed_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT STUDENTS_COURSE_GROUPS_PK PRIMARY KEY (student_id, course_group_id),
    CONSTRAINT STUDENTS_COURSE_GROUPS_STUDENT_FK
        FOREIGN KEY (student_id) REFERENCES STUDENTS(id)
        ON DELETE CASCADE,
    CONSTRAINT STUDENTS_COURSE_GROUPS_COURSE_GROUP_FK
        FOREIGN KEY (course_group_id) REFERENCES COURSE_GROUPS(id)
        ON DELETE CASCADE
);

CREATE TABLE STUDENTS_NOTIFICATIONS (
    student_id      NUMBER NOT NULL,
    notification_id NUMBER NOT NULL,
    is_read         NUMBER(1)
                        DEFAULT 0
                        NOT NULL
                        CONSTRAINT STUDENTS_NOTIFICATIONS_IS_READ_CHK
                            CHECK (is_read IN (0,1)),
    read_at         TIMESTAMP,
    CONSTRAINT STUDENTS_NOTIFICATIONS_PK PRIMARY KEY (student_id, notification_id),
    CONSTRAINT STUDENTS_NOTIFICATIONS_STUDENT_FK
        FOREIGN KEY (student_id) REFERENCES STUDENTS(id)
        ON DELETE CASCADE,
    CONSTRAINT STUDENTS_NOTIFICATIONS_NOTIFICATION_FK
        FOREIGN KEY (notification_id) REFERENCES NOTIFICATIONS(id)
        ON DELETE CASCADE
);

COMMENT ON TABLE STUDENTS IS 'الطلاب';
COMMENT ON COLUMN STUDENTS.id IS 'رقم الطالب';
COMMENT ON COLUMN STUDENTS.name IS 'الاسم';
COMMENT ON COLUMN STUDENTS.email IS 'البريد الإلكتروني';
COMMENT ON COLUMN STUDENTS.is_admin IS 'أدمن؟ (1/0)';
COMMENT ON COLUMN STUDENTS.created_at IS 'تاريخ الإنشاء';

COMMENT ON TABLE COHORTS IS 'المجموعات الدراسية';
COMMENT ON COLUMN COHORTS.id IS 'رقم المجموعة';
COMMENT ON COLUMN COHORTS.name IS 'الاسم';
COMMENT ON COLUMN COHORTS.created_at IS 'تاريخ الإنشاء';

COMMENT ON TABLE COURSES IS 'الكورسات';
COMMENT ON COLUMN COURSES.id IS 'رقم الكورس';
COMMENT ON COLUMN COURSES.name IS 'الاسم';
COMMENT ON COLUMN COURSES.created_at IS 'تاريخ الإنشاء';

COMMENT ON TABLE COURSE_GROUPS IS 'مجموعات الكورسات';
COMMENT ON COLUMN COURSE_GROUPS.id IS 'رقم مجموعة الكورس';
COMMENT ON COLUMN COURSE_GROUPS.course_id IS 'رقم الكورس';
COMMENT ON COLUMN COURSE_GROUPS.name IS 'الاسم';
COMMENT ON COLUMN COURSE_GROUPS.created_at IS 'تاريخ الإنشاء';

COMMENT ON TABLE DELIVERABLES IS 'التسليمات';
COMMENT ON COLUMN DELIVERABLES.id IS 'رقم التسليم';
COMMENT ON COLUMN DELIVERABLES.course_group_id IS 'رقم مجموعة الكورس';
COMMENT ON COLUMN DELIVERABLES.name IS 'الاسم';
COMMENT ON COLUMN DELIVERABLES.deadline IS 'الموعد النهائي';
COMMENT ON COLUMN DELIVERABLES.created_at IS 'تاريخ الإنشاء';

COMMENT ON TABLE NOTIFICATIONS IS 'الإشعارات';
COMMENT ON COLUMN NOTIFICATIONS.id IS 'رقم الإشعار';
COMMENT ON COLUMN NOTIFICATIONS.deliverable_id IS 'رقم التسليم';
COMMENT ON COLUMN NOTIFICATIONS.course_id IS 'رقم الكورس';
COMMENT ON COLUMN NOTIFICATIONS.title IS 'العنوان';
COMMENT ON COLUMN NOTIFICATIONS.message IS 'النص';
COMMENT ON COLUMN NOTIFICATIONS.created_at IS 'تاريخ الإنشاء';

COMMENT ON TABLE STUDENTS_COHORTS IS 'الطلاب والمجموعات';
COMMENT ON COLUMN STUDENTS_COHORTS.student_id IS 'رقم الطالب';
COMMENT ON COLUMN STUDENTS_COHORTS.cohort_id IS 'رقم المجموعة';
COMMENT ON COLUMN STUDENTS_COHORTS.enrolled_at IS 'تاريخ التسجيل';

COMMENT ON TABLE COHORTS_COURSES IS 'المجموعات والكورسات';
COMMENT ON COLUMN COHORTS_COURSES.cohort_id IS 'رقم المجموعة';
COMMENT ON COLUMN COHORTS_COURSES.course_id IS 'رقم الكورس';
COMMENT ON COLUMN COHORTS_COURSES.added_at IS 'تاريخ الإضافة';

COMMENT ON TABLE STUDENTS_COURSE_GROUPS IS 'الطلاب ومجموعات الكورسات';
COMMENT ON COLUMN STUDENTS_COURSE_GROUPS.student_id IS 'رقم الطالب';
COMMENT ON COLUMN STUDENTS_COURSE_GROUPS.course_group_id IS 'رقم مجموعة الكورس';
COMMENT ON COLUMN STUDENTS_COURSE_GROUPS.followed_at IS 'تاريخ المتابعة';

COMMENT ON TABLE STUDENTS_NOTIFICATIONS IS 'الطلاب والإشعارات';
COMMENT ON COLUMN STUDENTS_NOTIFICATIONS.student_id IS 'رقم الطالب';
COMMENT ON COLUMN STUDENTS_NOTIFICATIONS.notification_id IS 'رقم الإشعار';
COMMENT ON COLUMN STUDENTS_NOTIFICATIONS.is_read IS 'مقروء؟ (1/0)';
COMMENT ON COLUMN STUDENTS_NOTIFICATIONS.read_at IS 'تاريخ القراءة';

-- Indexes on foreign-key columns for join performance
CREATE INDEX COURSE_GROUPS_COURSE_ID_IDX ON COURSE_GROUPS(course_id);
CREATE INDEX DELIVERABLES_COURSE_GROUP_ID_IDX ON DELIVERABLES(course_group_id);
CREATE INDEX NOTIFICATIONS_DELIVERABLE_ID_IDX ON NOTIFICATIONS(deliverable_id);
CREATE INDEX NOTIFICATIONS_COURSE_ID_IDX ON NOTIFICATIONS(course_id);
CREATE INDEX STUDENTS_COHORTS_COHORT_ID_IDX ON STUDENTS_COHORTS(cohort_id);
CREATE INDEX COHORTS_COURSES_COURSE_ID_IDX ON COHORTS_COURSES(course_id);
CREATE INDEX STUDENTS_COURSE_GROUPS_COURSE_GROUP_ID_IDX ON STUDENTS_COURSE_GROUPS(course_group_id);
CREATE INDEX STUDENTS_NOTIFICATIONS_NOTIFICATION_ID_IDX ON STUDENTS_NOTIFICATIONS(notification_id);

CREATE OR REPLACE VIEW VW_STUDENT_COURSE_GROUPS AS
SELECT
    SCG.STUDENT_ID,
    S.NAME AS STUDENT_NAME,
    CG.ID AS COURSE_GROUP_ID,
    CG.NAME AS COURSE_GROUP_NAME,
    C.ID AS COURSE_ID,
    C.NAME AS COURSE_NAME,
    SCG.FOLLOWED_AT
FROM STUDENTS_COURSE_GROUPS SCG
JOIN STUDENTS S ON S.ID = SCG.STUDENT_ID
JOIN COURSE_GROUPS CG ON CG.ID = SCG.COURSE_GROUP_ID
JOIN COURSES C ON C.ID = CG.COURSE_ID;

CREATE OR REPLACE VIEW VW_DELIVERABLE_DETAILS AS
SELECT
    D.ID AS DELIVERABLE_ID,
    D.NAME AS DELIVERABLE_NAME,
    D.DEADLINE,
    CG.ID AS COURSE_GROUP_ID,
    CG.NAME AS COURSE_GROUP_NAME,
    C.ID AS COURSE_ID,
    C.NAME AS COURSE_NAME
FROM DELIVERABLES D
JOIN COURSE_GROUPS CG ON CG.ID = D.COURSE_GROUP_ID
JOIN COURSES C ON C.ID = CG.COURSE_ID;

CREATE OR REPLACE VIEW VW_STUDENT_NOTIFICATIONS AS
SELECT
    SN.STUDENT_ID,
    N.ID AS NOTIFICATION_ID,
    N.TITLE,
    N.MESSAGE,
    N.COURSE_ID,
    N.DELIVERABLE_ID,
    SN.IS_READ,
    SN.READ_AT,
    N.CREATED_AT
FROM STUDENTS_NOTIFICATIONS SN
JOIN NOTIFICATIONS N ON N.ID = SN.NOTIFICATION_ID;
